# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'JDragonSoapDemo' do

pod 'AFNetworking', '~> 3.1.0'
pod 'Reachability', '~> 3.2'
pod 'SVProgressHUD', '~> 1.1.3'

end

target 'JDragonSoapDemoTests' do

end

target 'JDragonSoapDemoUITests' do

end

